### ISSUE TITLE
Option to turn off auto gaining?

### ISSUE THREAD

**Issue by niieani** [tabahi/WebSpeechAnalyzer#1]
Hi Tabahi, your work here is super cool. So great to see a spectral analyzer (and more) running fully inside of a browser.
I was wondering if you considered adding an option to disable auto-gaining? Seems like highest peak dictates the overall gain for the whole audio segment, which is less than ideal for things like singing analysis, because further into the segment it looks as if the volume is going down.

**Comment by tabahi** [comment]
Hi, Thanks for the interest. The auto-gaining only affects the noise-gate and the pixel brightness during plotting. The end features have the raw power as it is (not even converted to DB, something like >10e5). In [segmentor.js](https://github.com/tabahi/WebSpeechAnalyzer/blob/main/app_assets/src/FormantAnalyzer/segmentor.js), the ratio of the pixel power to the `context_maximum` is used to determine the noise hysteresis. Anything below, `local_minimum` is filtered out. You can change these two variables to static simply by assigning a static value in function `amplitude_control(h_peak_amp)` in segmentor.js.

For higher output levels (>Mel-spectrum):

https://github.com/tabahi/WebSpeechAnalyzer/blob/82bce17f3372cc669e9d931abc8daad2ecd57947/app_assets/src/FormantAnalyzer/segmentor.js#L414


```
function amplitude_control(h_peak_amp)
{
    //h_peak_amp is the peak amplitude of the latest frame.
    context_maximum = 1000000;
    local_minimum = 10;
}
```


For lower output levels (<=Mel-spectrum):
https://github.com/tabahi/WebSpeechAnalyzer/blob/82bce17f3372cc669e9d931abc8daad2ecd57947/app_assets/src/FormantAnalyzer/segmentor.js#L596


Currently, there are no options on the interface to set the gain. In an old branch of the current fork, there were some options but then I removed them because it worked better dynamically. You can try the [older version here](https://tabahi.github.io/Mel-Spectrum-Analyzer/). I am trying to make it work in both noisy and clean environments but there seems to be no way without compromising the segmentation process. I will update you here when I update the current fork with a customizable noise-gate, I am working on it. Meanwhile, I welcome any new suggestions.

**Comment by niieani** [comment]
Awesome, thanks for the answer. I'll await the new version :)

**Comment by tabahi** [comment]
Added a new option for disabling auto-gaining. Set `auto_noise_gate: false`, and set manual values for `voiced_min_dB` and `voiced_max_dB` like this:
https://github.com/tabahi/WebSpeechAnalyzer/blob/1d31abf1300350090e052d3308706df8a83a80eb/simple.html#L106

Working demo [here](https://ar.tabahi.tech/WebSpeechAnalyzer/simple.html).
